prompts_file: "./examples/sdxl-prompts.yaml"

pretrained_model:
  name_or_path: "e:/models/sdxl/base/sd_xl_base_1.0_0.9vae.safetensors" # you can also use .ckpt or .safetensors models
  v2: false # true if model is v2.x
  v_pred: false # true if model uses v-prediction

network:
  type: "c3lier" # "lierla" or "c3lier"
  rank: 32
  alpha: 32.0
  training_method: "full" # selfattn, xattn, noxattn, or innoxattn

train:
  precision: "bfloat16"
  noise_scheduler: "ddim" # or "ddpm", "lms", "euler_a"
  iterations: 100
  lr: 1e-4
  optimizer: "adam8bit" # "AdamW"
  lr_scheduler: "constant"
  max_denoising_steps: 30

save:
  name: "woman2"
  path: "./output"
  per_steps: 50
  precision: "bfloat16"

logging:
  use_wandb: false
  verbose: true

other:
  use_xformers: true
